### PR TITLE
Optimize assets of repository

### PR DESCRIPTION
**Pull request by aladjadj**
Remove unused assets
Move css in the static folder and update the relative path of fonts

### CODE REVIEW

**Review by kepeket — COMMENTED** [review]
Pourquoi tu bouges les fonts en dehors de static, mais tu y mets les css?

**Comment by aladjadj** [comment]
Because fonts are called by css in the same parent directory "statics"
But fonts don't move.

**Review by depado — APPROVED** [review]

**Comment by xakraz** [comment]
To echo @kepeket's comment, it seems that the commit message does not express everything included in the changes :p 

Would it be possible to make the part about font explicit in the commit message @aladjadj ?

**Comment by kepeket** [comment]
> Because fonts are called by css in the same parent directory "statics"
> But fonts don't move.

Sorry, I browsed the tree and figured out fonts where already in `static`

**Review by kepeket — APPROVED** [review]

**Pull request merged**
